# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: main
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "org.springframework.boot:spring-boot-dependencies"
      - dependency-name: "org.apache.dubbo:dubbo-compiler"
      - dependency-name: "com.google.protobuf:protobuf-java"
      - dependency-name: "com.google.protobuf:protobuf-java-util"
      - dependency-name: "org.apache.maven.plugins:*"
      - dependency-name: "build.buf:protovalidate"
