spring:
  cloud:
    loadbalancer:
      zone: shanghai
    discoveryx:
      client:
        simple:
          instances:
            inventoryService:
              - instance-id: localhost
                host: localhost
                port: 12562
            orderService:
              - instance-id: localhost
                host: localhost
                port: 12561
