### BarService Greeting
POST http://{{barService}}/~barService/greeting
Content-Type: application/json
X-Gsvc-Caller: gtw

{
    "name": "gsvc",
    "age": 18
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        const type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
        client.assert(response.body.errCode === 0, "出错啦: " + response.body.errMsg);
        client.assert(response.body.data.name === "gsvc.bar@greeting", "响应不等于'gsvc.bar@greeting'")
    });
%}

### BooService Hello
POST http://{{barService}}/~barService/hello
Content-Type: application/json
X-Gsvc-Caller: gtw

{
    "name": "gsvc",
    "age": 18
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        const type = response.contentType.mimeType;
        client.assert(type === "text/event-stream", "Expected 'application/json' but received '" + type + "'");
        response.body.onEachLine((line, unsubscribe) => {
            client.log("response is: "+line)
            client.assert(line.data.name === "gsvc.bar@hello", line+" 不等于'gsvc.bar@hi'")
        },()=>{
            client.log("done!")
        })
    });
%}

### BooService Hi
POST http://{{barService}}/~barService/hi
Content-Type: application/json
X-Gsvc-Caller: gtw

{
    "name": "gsvc",
    "age": 18
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 400");
        const type = response.contentType.mimeType;
        client.assert(type === "text/event-stream", "Expected 'text/event-stream' but received '" + type + "'");
        response.body.onEachLine((line, unsubscribe) => {
            client.log("response is: "+line)
            client.assert(line.data.name === "gsvc.bar@hi", line+" 不等于'gsvc.bar@hi'")
        },()=>{
            client.log("done!")
        })
    });
%}

### Route - BooService bar/hi
POST http://{{barService}}/bar/hi
Content-Type: application/json

{
    "name": "gsvc",
    "age": 18
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        const type = response.contentType.mimeType;
        client.assert(type === "text/event-stream", "Expected 'text/event-stream' but received '" + type + "'");
        client.log("check response: ")
        response.body.onEachLine((line, unsubscribe) => {
            client.log("response is: "+line)
            client.assert(line.data.name === "gsvc.bar@hi", line+" 不等于'gsvc.bar@hi'")
        },()=>{
            client.log("done!")
        })
    });
%}


### Route - BooService bar/hello
POST http://{{barService}}/bar/hello
Content-Type: application/json

{
    "name": "gsvc",
    "age": 18
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        const type = response.contentType.mimeType;
        client.assert(type === "text/event-stream", "Expected 'application/json' but received '" + type + "'");
        response.body.onEachLine((line,unsubscribe)=>{
            client.assert(line.data.name === "gsvc.bar@hello", "响应不等于'gsvc.bar@hello'")
        },()=>{
            client.log("done!")
        })
    });
%}


### Route - BooService Greeting
POST http://{{barService}}/greeting
Content-Type: application/json

{
    "name": "gsvc",
    "age": 18
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        const type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
        client.assert(response.body.errCode === 0, "出错啦: " + response.body.errMsg);
        client.assert(response.body.data.name === "gsvc.bar@greeting", "响应不等于'gsvc.bar@greeting'")
    });
%}

### Route - BooService Greeting Hello
POST http://{{barService}}/greeting/hello
Content-Type: application/json

{
    "name": "gsvc",
    "age": 18
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        const type = response.contentType.mimeType;
        client.assert(type === "text/event-stream", "Expected 'text/event-stream' but received '" + type + "'");

         response.body.onEachLine((line,unsubscribe)=>{
            client.assert(line.data.name === "gsvc.bar@hello", "响应不等于'gsvc.bar@hello'")
        },()=>{
            client.log("done!")
        })
    });
%}

### Route - BooService Greet
POST http://{{barService}}/greet
Content-Type: application/json

{
    "name": "gsvc",
    "age": 18
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        const type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
        client.assert(response.body.errCode === 0, "出错啦: " + response.body.errMsg);
        client.assert(response.body.data.name === "gsvc.bar@greeting", "响应不等于'gsvc.bar@greeting'")
    });
%}

### Route - SaService - /sa/login
POST http://{{barService}}/sa/login
Content-Type: application/json

{
    "username": "admin",
    "password": "123456"
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        const type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
        client.assert(response.body.errCode === 0, "出错啦: " + response.body.errMsg);
        client.global.set("accessToken",response.body.data.accessToken)
        client.global.set("refreshToken",response.body.data.refreshToken)
    });
%}

### Route - SaService - /sa/info
POST http://{{barService}}/sa/info
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "gsvc"
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        const type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
        client.assert(response.body.errCode === 0, "出错啦: " + response.body.errMsg);
        client.assert(response.body.data.userName === "gsvc.admin", "userName != gsvc.admin");
        client.assert(response.body.data.uid === "admin", "uid != admin");
    });
%}

### Route - SaService - /sa/hi#after-login
POST http://{{barService}}/sa/hi
// @no-redirect
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "gsvc"
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        const type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
        client.assert(response.body.data.userName === "gsvc, admin",response.body.userName + "!= gsvc, admin")
    });
%}

### Auth - API - /token/refresh
POST http://{{barService}}/token/refresh
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "admin",
  "refreshToken": "{{refreshToken}}",
  "accessToken": "{{accessToken}}"
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        const type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'text/plain' but received '" + type + "'");
        client.global.set("accessToken",response.body.data.accessToken)
        client.global.set("refreshToken",response.body.data.refreshToken)
    });
%}

### Route - SaService - /sa/hi#after-refresh
POST http://{{barService}}/sa/hi
// @no-redirect
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "gsvc"
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        const type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
        client.assert(response.body.data.userName === "gsvc, admin",response.body.userName + "!= gsvc, admin")
    });
%}

### Auth - html - /logout#1
// @no-redirect
POST http://{{barService}}/logout
Accept: text/html
Authorization: Bearer {{accessToken}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 302, "Response status is not 200");
        const type = response.contentType.mimeType;
        client.assert(type === "text/html", "Expected 'text/plain' but received '" + type + "'");
        client.assert(response.headers.valueOf("Location").endsWith("/home") ,"'"+response.headers.valueOf('Location')+" not end with /home")
    });
%}

### Auth - API - /token/refresh#after-login
POST http://{{barService}}/token/refresh
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "admin",
  "refreshToken": "{{refreshToken}}",
  "accessToken": "{{accessToken}}"
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 401 || response.status === 500 , "Response status is not 500 or 401");
        const type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'text/plain' but received '" + type + "'");
        // client.assert(request.body.errCode === 500,"status != 500")
    });
%}

### Auth - API - /logout#2
POST http://{{barService}}/logout
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        const type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'text/plain' but received '" + type + "'");
        client.global.clear("accessToken")
        client.global.clear("refreshToken")
    });
%}

