// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeting_service.proto

package com.apzda.cloud.gsvc.proto;

public interface HelloRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:inventory.proto.HelloRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    String getName();

    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString getNameBytes();

    /**
     * <code>bytes file = 2;</code>
     * @return The file.
     */
    com.google.protobuf.ByteString getFile();

}
