server:
  port: 12564

grpc:
  server:
    port: 9090

logging:
  level:
    web: debug
    com.apzda: trace
    net.devh: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSSXXX} %highlight(%-5level) --- [%15.15t] %cyan(%-40.40logger{39}):%-4L - %msg%n"

apzda:
  cloud:
    service:
      MathService:
        grpc:
          enabled: true
