server:
  port: 12564

spring:
  application:
    name: math
  messages:
    basename: messages

grpc:
  server:
    port: 9090

logging:
  level:
    web: debug
    com.apzda: trace
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSSXXX} %highlight(%-5level) --- [%15.15t] %cyan(%-40.40logger{39}):%-4L - %X{tid} - %msg%n"

apzda:
  cloud:
    service:
      MathService:
        grpc:
          enabled: true
    security:
      meta-repo: redis
      jwt-key: abc12345678

management:
  tracing:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: tracing
# tracing
management:
  tracing:
    enabled: true
management.zipkin.tracing.endpoint: http://localhost:9411/api/v2/spans
management.tracing.sampling.probability: 1.0
apzda:
  cloud:
    reference:
      foo-service:
        svc-name: http://localhost:12561

---
spring.config.activate.on-profile: jdk21
spring.main.keep-alive: true
spring.threads.virtual.enabled: true
