spring:
  application:
    name: bar

---
spring:
  config:
    activate:
      on-profile: zipkin

management.zipkin.tracing.endpoint: http://localhost:9411/api/v2/spans
management.tracing.sampling.probability: 1.0
