spring:
  application:
    name: barService
  config:
    import: classpath:bar.yml
server:
  port: 32563
apzda:
  cloud:
    gtw-enabled: true
logging:
  level:
    web: debug
    com:
      apzda: trace
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSSXXX} %highlight(%-5level) --- [%15.15t] %cyan(%-40.40logger{39}):%-4L - %msg%n"
#
