spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            inventoryService:
              - instance-id: localhost
                host: localhost
                port: 12562
resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration: 5s
        cancel-running-future: true
      inventoryService:
        timeout-duration: 5s
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true