name: MicroService Architecture Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: micro-svc
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        java: [ '17','21' ]
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven
      - name: Install Gsvc Compiler
        run: mvn install -pl apzda-cloud-gsvc-compiler
      - name: Build with Maven
        run: mvn -B package -Djava.version=${{ matrix.java }} --file pom.xml
      - name: Run All Services
        uses: JarvusInnovations/background-action@v1
        with:
          working-directory: apzda-cloud-gsvc-demo
          wait-for: 5m
          tail: true
          run: |-
            java -jar demo-math-service/target/demo-math-service-fat.jar &
            java -jar demo-bar-service/target/demo-bar-service-fat.jar &
            java -jar demo-foo-service/target/demo-foo-service-fat.jar &
            java -jar demo-demo-service/target/demo-demo-service-fat.jar &
          wait-on: |-
            http-get://localhost:12561/actuator/health
            http-get://localhost:12562/actuator/health
            http-get://localhost:12563/demo/actuator/health
            tcp:localhost:9090
      - name: Download ijhttp tools
        run: docker pull jetbrains/intellij-http-client:233.11799.241
      - name: Execute HTTP requests
        run: |-
          docker run -it --rm -v ./apzda-cloud-gsvc-demo:/workdir jetbrains/intellij-http-client:233.11799.241 \
          --env-file http-docker.env.json --env dev \
          demo-test.http \
          bar-test.http \
          foo-test.http
