name: MicroService Architecture Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: micro-svc
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        java: [ '17','21' ]
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven
      - name: Install Gsvc Compiler
        run: mvn install -pl apzda-cloud-gsvc-compiler
      - name: Build with Maven
        run: mvn -B package -Djava.version=${{ matrix.java }} --file pom.xml
      - name: Run All Services
        uses: JarvusInnovations/background-action@v1
        with:
          working-directory: apzda-cloud-gsvc-demo
          wait-for: 5m
          tail: true
          run: |-
            java -jar demo-math-service/target/demo-math-service-fat.jar &
            java -jar demo-bar-service/target/demo-bar-service-fat.jar &
            java -jar demo-foo-service/target/demo-foo-service-fat.jar &
            java -jar demo-demo-service/target/demo-demo-service-fat.jar &
          wait-on: |-
            http-get://localhost:12561/actuator/health
            http-get://localhost:12562/actuator/health
            http-get://localhost:12563/demo/actuator/health
            tcp:localhost:9090
      - name: Download ijhttp tools
        run: |-
          curl -f -L -o ijhttp.zip "https://jb.gg/ijhttp/latest"
          unzip ijhttp.zip
          ./ijhttp/ijhttp --version
      - name: Execute HTTP requests
        run: |-
          ./ijhttp/ijhttp --env-file apzda-cloud-gsvc-demo/http-client.env.json --env dev apzda-cloud-gsvc-demo/demo-test.http
          ./ijhttp/ijhttp --env-file apzda-cloud-gsvc-demo/http-client.env.json --env dev apzda-cloud-gsvc-demo/bar-test.http
          ./ijhttp/ijhttp --env-file apzda-cloud-gsvc-demo/http-client.env.json --env dev apzda-cloud-gsvc-demo/foo-test.http
